#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00115.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/tz02a_dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/tz02a_pern.gz
cut -c31-31 data.dat | gzip -c - > data/tz02a_fbig.gz
cut -c32-33 data.dat | gzip -c - > data/tz02a_region.gz
cut -c34-36 data.dat | gzip -c - > data/tz02a_dist.gz
cut -c37-37 data.dat | gzip -c - > data/tz02a_urban.gz
cut -c38-38 data.dat | gzip -c - > data/tz02a_roof.gz
cut -c39-39 data.dat | gzip -c - > data/tz02a_walls.gz
cut -c40-40 data.dat | gzip -c - > data/tz02a_floor.gz
cut -c41-42 data.dat | gzip -c - > data/tz02a_rooms.gz
cut -c43-43 data.dat | gzip -c - > data/tz02a_fuelcook.gz
cut -c44-44 data.dat | gzip -c - > data/tz02a_lighting.gz
cut -c45-46 data.dat | gzip -c - > data/tz02a_watsrc.gz
cut -c47-47 data.dat | gzip -c - > data/tz02a_toilet.gz
cut -c48-48 data.dat | gzip -c - > data/tz02a_radio.gz
cut -c49-49 data.dat | gzip -c - > data/tz02a_phone.gz
cut -c50-50 data.dat | gzip -c - > data/tz02a_bicycle.gz
cut -c51-51 data.dat | gzip -c - > data/tz02a_whbarrow.gz
cut -c52-52 data.dat | gzip -c - > data/tz02a_iron.gz
cut -c53-53 data.dat | gzip -c - > data/tz02a_hoe.gz
cut -c54-54 data.dat | gzip -c - > data/tz02a_electric.gz
cut -c55-55 data.dat | gzip -c - > data/tz02a_deathser.gz
cut -c56-56 data.dat | gzip -c - > data/tz02a_deathsex.gz
cut -c57-58 data.dat | gzip -c - > data/tz02a_deathage.gz
cut -c59-63 data.dat | gzip -c - > data/tz02a_hhwt.gz
cut -c64-64 data.dat | gzip -c - > data/tz02a_collect.gz
cut -c65-67 data.dat | gzip -c - > data/pernum.gz
cut -c68-75 data.dat | gzip -c - > data/wtper.gz
cut -c76-77 data.dat | gzip -c - > data/tz02a_pernum.gz
cut -c78-78 data.dat | gzip -c - > data/tz02a_relate.gz
cut -c79-79 data.dat | gzip -c - > data/tz02a_sex.gz
cut -c80-81 data.dat | gzip -c - > data/tz02a_age.gz
cut -c82-82 data.dat | gzip -c - > data/tz02a_disab.gz
cut -c83-84 data.dat | gzip -c - > data/tz02a_citiz.gz
cut -c85-85 data.dat | gzip -c - > data/tz02a_marst.gz
cut -c86-86 data.dat | gzip -c - > data/tz02a_falive.gz
cut -c87-87 data.dat | gzip -c - > data/tz02a_malive.gz
cut -c88-89 data.dat | gzip -c - > data/tz02a_bpl.gz
cut -c90-91 data.dat | gzip -c - > data/tz02a_resid.gz
cut -c92-92 data.dat | gzip -c - > data/tz02a_areares.gz
cut -c93-94 data.dat | gzip -c - > data/tz02a_resid01.gz
cut -c95-95 data.dat | gzip -c - > data/tz02a_area01.gz
cut -c96-96 data.dat | gzip -c - > data/tz02a_lit.gz
cut -c97-97 data.dat | gzip -c - > data/tz02a_school.gz
cut -c98-99 data.dat | gzip -c - > data/tz02a_edattain.gz
cut -c100-101 data.dat | gzip -c - > data/tz02a_activyr.gz
cut -c102-103 data.dat | gzip -c - > data/tz02a_activwk.gz
cut -c104-104 data.dat | gzip -c - > data/tz02a_classwkr.gz
cut -c105-106 data.dat | gzip -c - > data/tz02a_occ.gz
cut -c107-108 data.dat | gzip -c - > data/tz02a_ind.gz
cut -c109-110 data.dat | gzip -c - > data/tz02a_mchildhh.gz
cut -c111-112 data.dat | gzip -c - > data/tz02a_fchildhh.gz
cut -c113-114 data.dat | gzip -c - > data/tz02a_mchaway.gz
cut -c115-116 data.dat | gzip -c - > data/tz02a_mchdead.gz
cut -c117-118 data.dat | gzip -c - > data/tz02a_fchdead.gz
cut -c119-119 data.dat | gzip -c - > data/tz02a_mbirths.gz
cut -c120-120 data.dat | gzip -c - > data/tz02a_fbirths.gz
cut -c121-122 data.dat | gzip -c - > data/tz02a_chborn.gz
cut -c123-124 data.dat | gzip -c - > data/tz02a_chsurv.gz
cut -c125-125 data.dat | gzip -c - > data/tz02a_bthlstyr.gz
cut -c126-127 data.dat | gzip -c - > data/tz02a_mchhhu.gz
cut -c128-129 data.dat | gzip -c - > data/tz02a_fchhhu.gz
cut -c130-131 data.dat | gzip -c - > data/tz02a_mchawayu.gz
cut -c132-133 data.dat | gzip -c - > data/tz02a_fchawayu.gz
cut -c134-135 data.dat | gzip -c - > data/tz02a_mchdeadu.gz
cut -c136-137 data.dat | gzip -c - > data/tz02a_fchdeadu.gz
cut -c138-142 data.dat | gzip -c - > data/tz02a_perwt.gz
rm data.dat
echo "  End vectorizing: " `date`
