#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00115.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/pern.gz
cut -c31-31 data.dat | gzip -c - > data/fbig.gz
cut -c32-33 data.dat | gzip -c - > data/region.gz
cut -c34-36 data.dat | gzip -c - > data/dist.gz
cut -c37-37 data.dat | gzip -c - > data/urban.gz
cut -c38-38 data.dat | gzip -c - > data/roof.gz
cut -c39-39 data.dat | gzip -c - > data/walls.gz
cut -c40-40 data.dat | gzip -c - > data/floor.gz
cut -c41-42 data.dat | gzip -c - > data/rooms.gz
cut -c43-43 data.dat | gzip -c - > data/fuelcook.gz
cut -c44-44 data.dat | gzip -c - > data/lighting.gz
cut -c45-46 data.dat | gzip -c - > data/watsrc.gz
cut -c47-47 data.dat | gzip -c - > data/toilet.gz
cut -c48-48 data.dat | gzip -c - > data/radio.gz
cut -c49-49 data.dat | gzip -c - > data/phone.gz
cut -c50-50 data.dat | gzip -c - > data/bicycle.gz
cut -c51-51 data.dat | gzip -c - > data/whbarrow.gz
cut -c52-52 data.dat | gzip -c - > data/iron.gz
cut -c53-53 data.dat | gzip -c - > data/hoe.gz
cut -c54-54 data.dat | gzip -c - > data/electric.gz
cut -c55-55 data.dat | gzip -c - > data/deathser.gz
cut -c56-56 data.dat | gzip -c - > data/deathsex.gz
cut -c57-58 data.dat | gzip -c - > data/deathage.gz
cut -c59-63 data.dat | gzip -c - > data/hhwt.gz
cut -c64-64 data.dat | gzip -c - > data/collect.gz
cut -c65-67 data.dat | gzip -c - > data/pernum.gz
cut -c68-75 data.dat | gzip -c - > data/wtper.gz
cut -c76-77 data.dat | gzip -c - > data/pernum.gz
cut -c78-78 data.dat | gzip -c - > data/relate.gz
cut -c79-79 data.dat | gzip -c - > data/sex.gz
cut -c80-81 data.dat | gzip -c - > data/age.gz
cut -c82-82 data.dat | gzip -c - > data/disab.gz
cut -c83-84 data.dat | gzip -c - > data/citiz.gz
cut -c85-85 data.dat | gzip -c - > data/marst.gz
cut -c86-86 data.dat | gzip -c - > data/falive.gz
cut -c87-87 data.dat | gzip -c - > data/malive.gz
cut -c88-89 data.dat | gzip -c - > data/bpl.gz
cut -c90-91 data.dat | gzip -c - > data/resid.gz
cut -c92-92 data.dat | gzip -c - > data/areares.gz
cut -c93-94 data.dat | gzip -c - > data/resid01.gz
cut -c95-95 data.dat | gzip -c - > data/area01.gz
cut -c96-96 data.dat | gzip -c - > data/lit.gz
cut -c97-97 data.dat | gzip -c - > data/school.gz
cut -c98-99 data.dat | gzip -c - > data/edattain.gz
cut -c100-101 data.dat | gzip -c - > data/activyr.gz
cut -c102-103 data.dat | gzip -c - > data/activwk.gz
cut -c104-104 data.dat | gzip -c - > data/classwkr.gz
cut -c105-106 data.dat | gzip -c - > data/occ.gz
cut -c107-108 data.dat | gzip -c - > data/ind.gz
cut -c109-110 data.dat | gzip -c - > data/mchildhh.gz
cut -c111-112 data.dat | gzip -c - > data/fchildhh.gz
cut -c113-114 data.dat | gzip -c - > data/mchaway.gz
cut -c115-116 data.dat | gzip -c - > data/mchdead.gz
cut -c117-118 data.dat | gzip -c - > data/fchdead.gz
cut -c119-119 data.dat | gzip -c - > data/mbirths.gz
cut -c120-120 data.dat | gzip -c - > data/fbirths.gz
cut -c121-122 data.dat | gzip -c - > data/chborn.gz
cut -c123-124 data.dat | gzip -c - > data/chsurv.gz
cut -c125-125 data.dat | gzip -c - > data/bthlstyr.gz
cut -c126-127 data.dat | gzip -c - > data/mchhhu.gz
cut -c128-129 data.dat | gzip -c - > data/fchhhu.gz
cut -c130-131 data.dat | gzip -c - > data/mchawayu.gz
cut -c132-133 data.dat | gzip -c - > data/fchawayu.gz
cut -c134-135 data.dat | gzip -c - > data/mchdeadu.gz
cut -c136-137 data.dat | gzip -c - > data/fchdeadu.gz
cut -c138-142 data.dat | gzip -c - > data/perwt.gz
rm data.dat
echo "  End vectorizing: " `date`
