#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00101.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00101.dat.gz.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/pern.gz
cut -c31-31 data.dat | gzip -c - > data/fbig.gz
cut -c32-32 data.dat | gzip -c - > data/fmphd.gz
cut -c33-34 data.dat | gzip -c - > data/region.gz
cut -c35-36 data.dat | gzip -c - > data/prov.gz
cut -c37-39 data.dat | gzip -c - > data/provrec.gz
cut -c40-40 data.dat | gzip -c - > data/bldtype.gz
cut -c41-42 data.dat | gzip -c - > data/walls.gz
cut -c43-43 data.dat | gzip -c - > data/bldrep.gz
cut -c44-45 data.dat | gzip -c - > data/yrblt.gz
cut -c46-47 data.dat | gzip -c - > data/space.gz
cut -c48-48 data.dat | gzip -c - > data/fuell.gz
cut -c49-49 data.dat | gzip -c - > data/fuelc.gz
cut -c50-51 data.dat | gzip -c - > data/watdrink.gz
cut -c52-52 data.dat | gzip -c - > data/watbath.gz
cut -c53-53 data.dat | gzip -c - > data/ownershp.gz
cut -c54-54 data.dat | gzip -c - > data/acquire.gz
cut -c55-55 data.dat | gzip -c - > data/finown.gz
cut -c56-56 data.dat | gzip -c - > data/fingov.gz
cut -c57-57 data.dat | gzip -c - > data/finbank.gz
cut -c58-58 data.dat | gzip -c - > data/finemp.gz
cut -c59-59 data.dat | gzip -c - > data/finpriv.gz
cut -c60-60 data.dat | gzip -c - > data/finoth.gz
cut -c61-61 data.dat | gzip -c - > data/ownlot.gz
cut -c62-62 data.dat | gzip -c - > data/rent.gz
cut -c63-63 data.dat | gzip -c - > data/garbage.gz
cut -c64-64 data.dat | gzip -c - > data/toilet.gz
cut -c65-65 data.dat | gzip -c - > data/radio.gz
cut -c66-66 data.dat | gzip -c - > data/tv.gz
cut -c67-67 data.dat | gzip -c - > data/refrig.gz
cut -c68-68 data.dat | gzip -c - > data/vcr.gz
cut -c69-69 data.dat | gzip -c - > data/phone.gz
cut -c70-70 data.dat | gzip -c - > data/washer.gz
cut -c71-71 data.dat | gzip -c - > data/vehicle.gz
cut -c72-72 data.dat | gzip -c - > data/landres.gz
cut -c73-73 data.dat | gzip -c - > data/landag.gz
cut -c74-74 data.dat | gzip -c - > data/landref.gz
cut -c75-75 data.dat | gzip -c - > data/landoth.gz
cut -c76-78 data.dat | gzip -c - > data/lang.gz
cut -c79-80 data.dat | gzip -c - > data/provint.gz
cut -c81-84 data.dat | gzip -c - > data/resintnd.gz
cut -c85-86 data.dat | gzip -c - > data/wthh.gz
cut -c87-89 data.dat | gzip -c - > data/pernum.gz
cut -c90-97 data.dat | gzip -c - > data/wtper.gz
cut -c98-99 data.dat | gzip -c - > data/pernum.gz
cut -c100-101 data.dat | gzip -c - > data/linenumo.gz
cut -c102-103 data.dat | gzip -c - > data/relate.gz
cut -c104-104 data.dat | gzip -c - > data/regist.gz
cut -c105-107 data.dat | gzip -c - > data/age.gz
cut -c108-108 data.dat | gzip -c - > data/sex.gz
cut -c109-109 data.dat | gzip -c - > data/overseas.gz
cut -c110-110 data.dat | gzip -c - > data/marst.gz
cut -c111-112 data.dat | gzip -c - > data/relig.gz
cut -c113-115 data.dat | gzip -c - > data/bplcntry.gz
cut -c116-116 data.dat | gzip -c - > data/disab.gz
cut -c117-118 data.dat | gzip -c - > data/disabtyp.gz
cut -c119-121 data.dat | gzip -c - > data/ethnic.gz
cut -c122-122 data.dat | gzip -c - > data/lit.gz
cut -c123-123 data.dat | gzip -c - > data/langfil.gz
cut -c124-124 data.dat | gzip -c - > data/lange.gz
cut -c125-125 data.dat | gzip -c - > data/school.gz
cut -c126-126 data.dat | gzip -c - > data/schtype.gz
cut -c127-128 data.dat | gzip -c - > data/edattan.gz
cut -c129-130 data.dat | gzip -c - > data/prov5yr.gz
cut -c131-132 data.dat | gzip -c - > data/prov10yr.gz
cut -c133-136 data.dat | gzip -c - > data/mun10yr.gz
cut -c137-138 data.dat | gzip -c - > data/occ2.gz
cut -c139-141 data.dat | gzip -c - > data/occ.gz
cut -c142-143 data.dat | gzip -c - > data/ind.gz
cut -c144-144 data.dat | gzip -c - > data/classwk.gz
cut -c145-146 data.dat | gzip -c - > data/wtper.gz
rm data.dat
echo "  End vectorizing: " `date`
