#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00049.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/pern.gz
cut -c31-32 data.dat | gzip -c - > data/prov.gz
cut -c33-33 data.dat | gzip -c - > data/houstype.gz
cut -c34-34 data.dat | gzip -c - > data/floor.gz
cut -c35-35 data.dat | gzip -c - > data/roof.gz
cut -c36-36 data.dat | gzip -c - > data/ceiling.gz
cut -c37-37 data.dat | gzip -c - > data/watsup.gz
cut -c38-38 data.dat | gzip -c - > data/watsrc.gz
cut -c39-39 data.dat | gzip -c - > data/bath.gz
cut -c40-40 data.dat | gzip -c - > data/toilet.gz
cut -c41-41 data.dat | gzip -c - > data/sewage.gz
cut -c42-42 data.dat | gzip -c - > data/privbath.gz
cut -c43-43 data.dat | gzip -c - > data/fuelck.gz
cut -c44-45 data.dat | gzip -c - > data/bedrms.gz
cut -c46-47 data.dat | gzip -c - > data/rooms.gz
cut -c48-48 data.dat | gzip -c - > data/ownrshp.gz
cut -c49-49 data.dat | gzip -c - > data/landown.gz
cut -c50-50 data.dat | gzip -c - > data/refrig.gz
cut -c51-51 data.dat | gzip -c - > data/computr.gz
cut -c52-52 data.dat | gzip -c - > data/cellphon.gz
cut -c53-53 data.dat | gzip -c - > data/phone.gz
cut -c54-56 data.dat | gzip -c - > data/pernum.gz
cut -c57-64 data.dat | gzip -c - > data/wtper.gz
cut -c65-66 data.dat | gzip -c - > data/pernum.gz
cut -c67-67 data.dat | gzip -c - > data/relate.gz
cut -c68-68 data.dat | gzip -c - > data/sex.gz
cut -c69-71 data.dat | gzip -c - > data/age.gz
cut -c72-73 data.dat | gzip -c - > data/birthmn.gz
cut -c74-77 data.dat | gzip -c - > data/birthyr.gz
cut -c78-78 data.dat | gzip -c - > data/bpl.gz
cut -c79-81 data.dat | gzip -c - > data/country.gz
cut -c82-82 data.dat | gzip -c - > data/lit.gz
cut -c83-83 data.dat | gzip -c - > data/school.gz
cut -c84-85 data.dat | gzip -c - > data/edlev.gz
cut -c86-87 data.dat | gzip -c - > data/grade.gz
cut -c88-90 data.dat | gzip -c - > data/edattan.gz
cut -c91-91 data.dat | gzip -c - > data/secsch.gz
cut -c92-92 data.dat | gzip -c - > data/levelsch.gz
cut -c93-93 data.dat | gzip -c - > data/compuse.gz
cut -c94-94 data.dat | gzip -c - > data/wk1hr.gz
cut -c95-95 data.dat | gzip -c - > data/wkinf.gz
cut -c96-96 data.dat | gzip -c - > data/wkaway.gz
cut -c97-97 data.dat | gzip -c - > data/wklook.gz
rm data.dat
echo "  End vectorizing: " `date`
