#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00116.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00116.dat.gz.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-27 data.dat | gzip -c - > data/dwnum.gz
cut -c28-29 data.dat | gzip -c - > data/pern.gz
cut -c30-30 data.dat | gzip -c - > data/fbig.gz
cut -c31-31 data.dat | gzip -c - > data/region.gz
cut -c32-33 data.dat | gzip -c - > data/prov.gz
cut -c34-34 data.dat | gzip -c - > data/area.gz
cut -c35-35 data.dat | gzip -c - > data/hhtype.gz
cut -c36-36 data.dat | gzip -c - > data/langhh.gz
cut -c37-38 data.dat | gzip -c - > data/langhho.gz
cut -c39-40 data.dat | gzip -c - > data/dwelltyp.gz
cut -c41-41 data.dat | gzip -c - > data/walls.gz
cut -c42-42 data.dat | gzip -c - > data/ownershp.gz
cut -c43-43 data.dat | gzip -c - > data/landown.gz
cut -c44-44 data.dat | gzip -c - > data/fuelcook.gz
cut -c45-45 data.dat | gzip -c - > data/toilet.gz
cut -c46-47 data.dat | gzip -c - > data/water.gz
cut -c48-49 data.dat | gzip -c - > data/watsup.gz
cut -c50-51 data.dat | gzip -c - > data/tv.gz
cut -c52-53 data.dat | gzip -c - > data/radio.gz
cut -c54-55 data.dat | gzip -c - > data/fridge.gz
cut -c56-57 data.dat | gzip -c - > data/washer.gz
cut -c58-59 data.dat | gzip -c - > data/phone.gz
cut -c60-61 data.dat | gzip -c - > data/aircond.gz
cut -c62-63 data.dat | gzip -c - > data/fan.gz
cut -c64-65 data.dat | gzip -c - > data/car.gz
cut -c66-67 data.dat | gzip -c - > data/moto.gz
cut -c68-69 data.dat | gzip -c - > data/bike.gz
cut -c70-71 data.dat | gzip -c - > data/agmach.gz
cut -c72-73 data.dat | gzip -c - > data/tractor.gz
cut -c74-80 data.dat | gzip -c - > data/hhwt.gz
cut -c81-83 data.dat | gzip -c - > data/pernum.gz
cut -c84-91 data.dat | gzip -c - > data/wtper.gz
cut -c92-93 data.dat | gzip -c - > data/pernum.gz
cut -c94-94 data.dat | gzip -c - > data/relate.gz
cut -c95-95 data.dat | gzip -c - > data/sex.gz
cut -c96-98 data.dat | gzip -c - > data/ager.gz
cut -c99-100 data.dat | gzip -c - > data/birthmo.gz
cut -c101-103 data.dat | gzip -c - > data/birthyr.gz
cut -c104-104 data.dat | gzip -c - > data/relig.gz
cut -c105-106 data.dat | gzip -c - > data/nation.gz
cut -c107-108 data.dat | gzip -c - > data/gradeatt.gz
cut -c109-109 data.dat | gzip -c - > data/lit.gz
cut -c110-111 data.dat | gzip -c - > data/higrade.gz
cut -c112-112 data.dat | gzip -c - > data/marst.gz
cut -c113-116 data.dat | gzip -c - > data/occ3.gz
cut -c117-119 data.dat | gzip -c - > data/ind3.gz
cut -c120-121 data.dat | gzip -c - > data/classwk.gz
cut -c122-125 data.dat | gzip -c - > data/occwk3.gz
cut -c126-126 data.dat | gzip -c - > data/seeking.gz
cut -c127-128 data.dat | gzip -c - > data/reaswork.gz
cut -c129-130 data.dat | gzip -c - > data/chsurv.gz
cut -c131-132 data.dat | gzip -c - > data/chdead.gz
cut -c133-133 data.dat | gzip -c - > data/births.gz
cut -c134-135 data.dat | gzip -c - > data/bpl.gz
cut -c136-136 data.dat | gzip -c - > data/durres.gz
cut -c137-139 data.dat | gzip -c - > data/prevres.gz
cut -c140-140 data.dat | gzip -c - > data/prevdist.gz
cut -c141-141 data.dat | gzip -c - > data/prevplc.gz
cut -c142-143 data.dat | gzip -c - > data/migreas.gz
cut -c144-145 data.dat | gzip -c - > data/age.gz
cut -c146-147 data.dat | gzip -c - > data/chborn.gz
cut -c148-154 data.dat | gzip -c - > data/perwt.gz
rm data.dat
echo "  End vectorizing: " `date`
