#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00091.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00091.dat.gz.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/pern.gz
cut -c31-31 data.dat | gzip -c - > data/fbig.gz
cut -c32-32 data.dat | gzip -c - > data/region.gz
cut -c33-34 data.dat | gzip -c - > data/circle.gz
cut -c35-35 data.dat | gzip -c - > data/area.gz
cut -c36-36 data.dat | gzip -c - > data/urban.gz
cut -c37-37 data.dat | gzip -c - > data/typehh.gz
cut -c38-38 data.dat | gzip -c - > data/emigmal.gz
cut -c39-39 data.dat | gzip -c - > data/emigfem.gz
cut -c40-40 data.dat | gzip -c - > data/emigtot.gz
cut -c41-41 data.dat | gzip -c - > data/regtyp.gz
cut -c42-43 data.dat | gzip -c - > data/dwtype.gz
cut -c44-44 data.dat | gzip -c - > data/walls.gz
cut -c45-45 data.dat | gzip -c - > data/roof.gz
cut -c46-46 data.dat | gzip -c - > data/floor.gz
cut -c47-48 data.dat | gzip -c - > data/light.gz
cut -c49-50 data.dat | gzip -c - > data/watsrc.gz
cut -c51-52 data.dat | gzip -c - > data/fuelck.gz
cut -c53-54 data.dat | gzip -c - > data/toilet.gz
cut -c55-56 data.dat | gzip -c - > data/ownershp.gz
cut -c57-58 data.dat | gzip -c - > data/rooms.gz
cut -c59-59 data.dat | gzip -c - > data/stove.gz
cut -c60-61 data.dat | gzip -c - > data/trash.gz
cut -c62-63 data.dat | gzip -c - > data/sewer.gz
cut -c64-64 data.dat | gzip -c - > data/death12m.gz
cut -c65-65 data.dat | gzip -c - > data/ndeaths.gz
cut -c66-66 data.dat | gzip -c - > data/emighh.gz
cut -c67-67 data.dat | gzip -c - > data/nemighh.gz
cut -c68-68 data.dat | gzip -c - > data/migrecs.gz
cut -c69-69 data.dat | gzip -c - > data/nmort.gz
cut -c70-72 data.dat | gzip -c - > data/pernum.gz
cut -c73-80 data.dat | gzip -c - > data/wtper.gz
cut -c81-82 data.dat | gzip -c - > data/pernum.gz
cut -c83-83 data.dat | gzip -c - > data/sex.gz
cut -c84-85 data.dat | gzip -c - > data/relate.gz
cut -c86-86 data.dat | gzip -c - > data/resident.gz
cut -c87-87 data.dat | gzip -c - > data/religion.gz
cut -c88-88 data.dat | gzip -c - > data/brthreg.gz
cut -c89-90 data.dat | gzip -c - > data/birthmo.gz
cut -c91-94 data.dat | gzip -c - > data/birthyr.gz
cut -c95-96 data.dat | gzip -c - > data/age.gz
cut -c97-98 data.dat | gzip -c - > data/agemo.gz
cut -c99-101 data.dat | gzip -c - > data/bplctry.gz
cut -c102-103 data.dat | gzip -c - > data/bplregn.gz
cut -c104-105 data.dat | gzip -c - > data/bpl.gz
cut -c106-108 data.dat | gzip -c - > data/nation.gz
cut -c109-109 data.dat | gzip -c - > data/disab.gz
cut -c110-112 data.dat | gzip -c - > data/prevctry.gz
cut -c113-114 data.dat | gzip -c - > data/prevres2.gz
cut -c115-116 data.dat | gzip -c - > data/prevres.gz
cut -c117-118 data.dat | gzip -c - > data/durres.gz
cut -c119-119 data.dat | gzip -c - > data/livfat.gz
cut -c120-120 data.dat | gzip -c - > data/livmot.gz
cut -c121-121 data.dat | gzip -c - > data/school.gz
cut -c122-123 data.dat | gzip -c - > data/edlevel.gz
cut -c124-125 data.dat | gzip -c - > data/class.gz
cut -c126-129 data.dat | gzip -c - > data/edattend.gz
cut -c130-131 data.dat | gzip -c - > data/diploma.gz
cut -c132-133 data.dat | gzip -c - > data/langnat.gz
cut -c134-135 data.dat | gzip -c - > data/langflu.gz
cut -c136-137 data.dat | gzip -c - > data/empstat.gz
cut -c138-141 data.dat | gzip -c - > data/occ.gz
cut -c142-143 data.dat | gzip -c - > data/classwk.gz
cut -c144-145 data.dat | gzip -c - > data/ind.gz
cut -c146-147 data.dat | gzip -c - > data/agric.gz
cut -c148-148 data.dat | gzip -c - > data/marst.gz
cut -c149-149 data.dat | gzip -c - > data/lit.gz
cut -c150-151 data.dat | gzip -c - > data/chbornm.gz
cut -c152-153 data.dat | gzip -c - > data/chbornf.gz
cut -c154-155 data.dat | gzip -c - > data/chsurvm.gz
cut -c156-157 data.dat | gzip -c - > data/chsurvf.gz
cut -c158-158 data.dat | gzip -c - > data/bth12mal.gz
cut -c159-159 data.dat | gzip -c - > data/bthfem12.gz
rm data.dat
echo "  End vectorizing: " `date`
