variables.metadata.autogenerated.create <- function() {
  # Must be run in samplename directory
  source("../../processing/Rfunctions1/variable.metadata.autocreate.R")
  source("../../processing/Rfunctions2/getvariable.R")
  source("../../processing/Rfunctions2/getcodebook.R")
  x <- readRDS("metadata/vnames.vdescriptions.rds")
  vnames <- x[, "vname"]
  rowrm  <- vnames == "cntry" | vnames == "year" | vnames == "sample"
  y <- x[!rowrm, c("vdescription", "vname")]
  vnames <- y[, "vname"]
  z <- cbind(y, qref="", unit="", length=NA, cat="", ncodes=NA, cbook="",
             nvals=NA, mvcode=NA, uvcode=NA, fvar1="", fvals1="",
             fvar2="", fvals2="", fvar3="", fvals3="",
             fvar4="", fvals4="")
  ccols <- c("qref", "unit", "cat", "cbook", "mvcode", "uvcode",
             "fvar1", "fvals1", "fvar2", "fvals2", 
             "fvar3", "fvals3", "fvar4", "fvals4")
  for (j in 1:length(ccols)) {
    z[, ccols[j]] <- as.character(z[, ccols[j]])
  }
  ncols <- c("length", "ncodes", "nvals")
  for (j in 1:length(ncols)) {
    z[, ncols[j]] <- as.numeric(z[, ncols[j]])
  }
  for (i in 1:(dim(z)[1])) {
    vmd <- variable.metadata.autocreate(z[i, "vname"])
    cat(paste(formatC(i, width=3, flag="0"), ": ", vmd$vname, " ...\n", sep=""))
    z[i, "unit"]   <- vmd$unit
    z[i, "length"] <- vmd$length
    z[i, "ncodes"] <- vmd$ncodes
    z[i, "cbook"]  <- vmd$cbook
    z[i, "nvals"]  <- vmd$nvals
    z[i, "mvcode"] <- vmd$mvcode
    z[i, "uvcode"] <- vmd$uvcode
  }
  saveRDS(z, "metadata/variables.metadata.autogenerated.rds")
  library(XLConnect)
  wb <- loadWorkbook("metadata/variables.metadata.autogenerated.xlsx", create=TRUE)
  createSheet(wb, name="vars.metadata.autogenerated")
  writeWorksheet(wb, z, sheet="vars.metadata.autogenerated", startRow=1, startCol=1)
  saveWorkbook(wb)
  cat("Workbook 'variables.metadata.autogenerated.xlsx' created in 'metadata' directory\n")
  cat("Now copy *.autogenerated.xlsx to *.manuallyedited.xlsx, check, and fill in\n")
}

