variables.metadata.spreadsheet.initialize <- function() {
  # Must be run in samplename directory
  source("../../processing/Rfunctions1/variable.metadata.autocreate.R")
  source("../../processing/Rfunctions2/getvariable.R")
  source("../../processing/Rfunctions2/getcodebook.R")
  x <- readRDS("metadata/vnames.vdescriptions.rds")
  vnames <- x[, "vname"]
  rowrm  <- vnames == "cntry" | vnames == "year" | vnames == "sample"
  y <- x[!rowrm, c("vdescription", "vname")]
  vnames <- y[, "vname"]
  z <- cbind(y, qref="", unit="", length=0, cat="", ncodes=0, cbook="",
             nvals=0, mvcode=0, uvcode=0, fvar1="NA", fvals1="NA",
             fvar2="NA", fvals2="NA", fvar3="NA", fvals3="NA",
             fvar4="NA", fvals4="NA")
  ccols <- c("qref", "unit", "cat", "cbook",
             "fvar1", "fvals1", "fvar2", "fvals2", 
             "fvar3", "fvals3", "fvar4", "fvals4")
  for (j in 1:length(ccols)) {
    z[, ccols[j]] <- as.character(z[, ccols[j]])
  }
  ncols <- c("length", "ncodes", "nvals", "mvcode", "uvcode")
  for (j in 1:length(ncols)) {
    z[, ncols[j]] <- as.numeric(z[, ncols[j]])
  }
  for (i in 1:(dim(z)[1])) {
    vmd <- variable.metadata.create(z[i, "vname"])
    z[i, "unit"]   <- vmd$unit
    z[i, "length"] <- vmd$length
    z[i, "ncodes"] <- vmd$ncodes
    z[i, "cbook"]  <- vmd$cbook
    z[i, "nvals"]  <- vmd$nvals
  }
  saveRDS(z, "metadata/variables.metadata.autogenerated.rds")
  library(XLConnect)
  wb <- loadWorkbook("metadata/variables.metadata.xls", create=TRUE)
  createSheet(wb, name="vars.metadata.autogenerated")
  createSheet(wb, name="vars.metadata.manuallyedited")
  writeWorksheet(wb, z, sheet="vars.metadata.autogenerated", startRow=1, startCol=1)
  writeWorksheet(wb, z, sheet="vars.metadata.manuallyedited", startRow=1, startCol=1)
  saveWorkbook(wb)
  cat("Workbook 'variables.metadata.xls' created in 'metadata' directory, ready for manual editing\n")
}

