#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00087.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00087.dat.gz.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/hhnum.gz
cut -c31-32 data.dat | gzip -c - > data/hhn.gz
cut -c33-34 data.dat | gzip -c - > data/pernd.gz
cut -c35-36 data.dat | gzip -c - > data/pern.gz
cut -c37-37 data.dat | gzip -c - > data/structnum.gz
cut -c38-38 data.dat | gzip -c - > data/restype.gz
cut -c39-39 data.dat | gzip -c - > data/stories.gz
cut -c40-40 data.dat | gzip -c - > data/wall.gz
cut -c41-41 data.dat | gzip -c - > data/construct.gz
cut -c42-42 data.dat | gzip -c - > data/seismic.gz
cut -c43-44 data.dat | gzip -c - > data/occrestype.gz
cut -c45-45 data.dat | gzip -c - > data/occupancy.gz
cut -c46-48 data.dat | gzip -c - > data/area.gz
cut -c49-51 data.dat | gzip -c - > data/livarea.gz
cut -c52-53 data.dat | gzip -c - > data/rooms.gz
cut -c54-54 data.dat | gzip -c - > data/region.gz
cut -c55-59 data.dat | gzip -c - > data/dist.gz
cut -c60-60 data.dat | gzip -c - > data/urban.gz
cut -c61-63 data.dat | gzip -c - > data/pernum.gz
cut -c64-71 data.dat | gzip -c - > data/wtper.gz
cut -c72-73 data.dat | gzip -c - > data/pernum.gz
cut -c74-75 data.dat | gzip -c - > data/geogaway.gz
cut -c76-76 data.dat | gzip -c - > data/awaytime.gz
cut -c77-77 data.dat | gzip -c - > data/whyaway.gz
cut -c78-79 data.dat | gzip -c - > data/relate.gz
cut -c80-81 data.dat | gzip -c - > data/parentloc.gz
cut -c82-82 data.dat | gzip -c - > data/sex.gz
cut -c83-83 data.dat | gzip -c - > data/resstatus.gz
cut -c84-85 data.dat | gzip -c - > data/mob.gz
cut -c86-89 data.dat | gzip -c - > data/yob.gz
cut -c90-91 data.dat | gzip -c - > data/age.gz
cut -c92-94 data.dat | gzip -c - > data/nation.gz
cut -c95-97 data.dat | gzip -c - > data/lang1.gz
cut -c98-100 data.dat | gzip -c - > data/lang2.gz
cut -c101-103 data.dat | gzip -c - > data/lang3.gz
cut -c104-108 data.dat | gzip -c - > data/bpl.gz
cut -c109-111 data.dat | gzip -c - > data/bplctry.gz
cut -c112-112 data.dat | gzip -c - > data/citizen.gz
cut -c113-116 data.dat | gzip -c - > data/yrmoved.gz
cut -c117-117 data.dat | gzip -c - > data/whymoved.gz
cut -c118-118 data.dat | gzip -c - > data/marst.gz
cut -c119-120 data.dat | gzip -c - > data/sploc.gz
cut -c121-122 data.dat | gzip -c - > data/edlevel.gz
cut -c123-123 data.dat | gzip -c - > data/lit.gz
cut -c124-124 data.dat | gzip -c - > data/degree.gz
cut -c125-125 data.dat | gzip -c - > data/edtype.gz
cut -c126-126 data.dat | gzip -c - > data/preschool.gz
cut -c127-127 data.dat | gzip -c - > data/incsrc.gz
cut -c128-131 data.dat | gzip -c - > data/ind.gz
cut -c132-132 data.dat | gzip -c - > data/empstat.gz
cut -c133-133 data.dat | gzip -c - > data/lookwk.gz
cut -c134-134 data.dat | gzip -c - > data/nowkreas.gz
cut -c135-136 data.dat | gzip -c - > data/chborn.gz
cut -c137-138 data.dat | gzip -c - > data/chbornm.gz
cut -c139-140 data.dat | gzip -c - > data/chbornf.gz
cut -c141-142 data.dat | gzip -c - > data/chsurv.gz
cut -c143-144 data.dat | gzip -c - > data/chsurvm.gz
cut -c145-146 data.dat | gzip -c - > data/chsurvf.gz
cut -c147-148 data.dat | gzip -c - > data/chaway.gz
cut -c149-150 data.dat | gzip -c - > data/chawaym.gz
cut -c151-152 data.dat | gzip -c - > data/chawayf.gz
rm data.dat
echo "  End vectorizing: " `date`
