#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00065.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-29 data.dat | gzip -c - > data/hhnum.gz
cut -c30-30 data.dat | gzip -c - > data/hhn.gz
cut -c31-32 data.dat | gzip -c - > data/pernd.gz
cut -c33-34 data.dat | gzip -c - > data/pern.gz
cut -c35-35 data.dat | gzip -c - > data/fbig.gz
cut -c36-37 data.dat | gzip -c - > data/prov.gz
cut -c38-38 data.dat | gzip -c - > data/collect.gz
cut -c39-39 data.dat | gzip -c - > data/dwtype.gz
cut -c40-40 data.dat | gzip -c - > data/hhstat.gz
cut -c41-42 data.dat | gzip -c - > data/builtyr.gz
cut -c43-44 data.dat | gzip -c - > data/rooms.gz
cut -c45-45 data.dat | gzip -c - > data/roomss.gz
cut -c46-47 data.dat | gzip -c - > data/roomsb.gz
cut -c48-48 data.dat | gzip -c - > data/kitch.gz
cut -c49-49 data.dat | gzip -c - > data/watfac.gz
cut -c50-50 data.dat | gzip -c - > data/watsup.gz
cut -c51-51 data.dat | gzip -c - > data/watwast.gz
cut -c52-52 data.dat | gzip -c - > data/bath.gz
cut -c53-53 data.dat | gzip -c - > data/toilet.gz
cut -c54-54 data.dat | gzip -c - > data/toiletl.gz
cut -c55-55 data.dat | gzip -c - > data/power.gz
cut -c56-58 data.dat | gzip -c - > data/pernum.gz
cut -c59-66 data.dat | gzip -c - > data/wtper.gz
cut -c67-68 data.dat | gzip -c - > data/pernum.gz
cut -c69-69 data.dat | gzip -c - > data/relate.gz
cut -c70-71 data.dat | gzip -c - > data/parloco.gz
cut -c72-73 data.dat | gzip -c - > data/sploco.gz
cut -c74-74 data.dat | gzip -c - > data/sex.gz
cut -c75-77 data.dat | gzip -c - > data/age.gz
cut -c78-78 data.dat | gzip -c - > data/race.gz
cut -c79-79 data.dat | gzip -c - > data/bplresid.gz
cut -c80-82 data.dat | gzip -c - > data/bplctry.gz
cut -c83-85 data.dat | gzip -c - > data/bplprov.gz
cut -c86-89 data.dat | gzip -c - > data/bplmuni.gz
cut -c90-90 data.dat | gzip -c - > data/bornhere.gz
cut -c91-93 data.dat | gzip -c - > data/resctry.gz
cut -c94-96 data.dat | gzip -c - > data/resprov.gz
cut -c97-100 data.dat | gzip -c - > data/resmuni.gz
cut -c101-102 data.dat | gzip -c - > data/resdur.gz
cut -c103-103 data.dat | gzip -c - > data/edlev.gz
cut -c104-105 data.dat | gzip -c - > data/degree.gz
cut -c106-106 data.dat | gzip -c - > data/marst.gz
cut -c107-108 data.dat | gzip -c - > data/empstat.gz
cut -c109-111 data.dat | gzip -c - > data/occ.gz
cut -c112-113 data.dat | gzip -c - > data/ind.gz
rm data.dat
echo "  End vectorizing: " `date`
