#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00077.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-27 data.dat | gzip -c - > data/dwnum.gz
cut -c28-28 data.dat | gzip -c - > data/hhnum.gz
cut -c29-29 data.dat | gzip -c - > data/hhn.gz
cut -c30-31 data.dat | gzip -c - > data/pernd.gz
cut -c32-33 data.dat | gzip -c - > data/pern.gz
cut -c34-34 data.dat | gzip -c - > data/fgq.gz
cut -c35-36 data.dat | gzip -c - > data/famn.gz
cut -c37-37 data.dat | gzip -c - > data/fbig.gz
cut -c38-39 data.dat | gzip -c - > data/story.gz
cut -c40-40 data.dat | gzip -c - > data/bldty.gz
cut -c41-44 data.dat | gzip -c - > data/conyr.gz
cut -c45-45 data.dat | gzip -c - > data/dwtype.gz
cut -c46-46 data.dat | gzip -c - > data/occup.gz
cut -c47-47 data.dat | gzip -c - > data/ownty.gz
cut -c48-48 data.dat | gzip -c - > data/room.gz
cut -c49-49 data.dat | gzip -c - > data/kitch.gz
cut -c50-50 data.dat | gzip -c - > data/kitchs.gz
cut -c51-51 data.dat | gzip -c - > data/baths.gz
cut -c52-52 data.dat | gzip -c - > data/bathsn.gz
cut -c53-55 data.dat | gzip -c - > data/floorspr.gz
cut -c56-56 data.dat | gzip -c - > data/watsup.gz
cut -c57-57 data.dat | gzip -c - > data/hotwat.gz
cut -c58-58 data.dat | gzip -c - > data/gas.gz
cut -c59-59 data.dat | gzip -c - > data/heat.gz
cut -c60-60 data.dat | gzip -c - > data/toilet.gz
cut -c61-61 data.dat | gzip -c - > data/sewer.gz
cut -c62-62 data.dat | gzip -c - > data/comfort.gz
cut -c63-63 data.dat | gzip -c - > data/tenure.gz
cut -c64-66 data.dat | gzip -c - > data/pernum.gz
cut -c67-74 data.dat | gzip -c - > data/wtper.gz
cut -c75-76 data.dat | gzip -c - > data/pernum.gz
cut -c77-77 data.dat | gzip -c - > data/hhnumo.gz
cut -c78-78 data.dat | gzip -c - > data/relatef1.gz
cut -c79-79 data.dat | gzip -c - > data/tenurep.gz
cut -c80-80 data.dat | gzip -c - > data/sex.gz
cut -c81-83 data.dat | gzip -c - > data/age.gz
cut -c84-84 data.dat | gzip -c - > data/citizen.gz
cut -c85-85 data.dat | gzip -c - > data/marst.gz
cut -c86-86 data.dat | gzip -c - > data/marn.gz
cut -c87-87 data.dat | gzip -c - > data/conun.gz
cut -c88-89 data.dat | gzip -c - > data/chborn.gz
cut -c90-90 data.dat | gzip -c - > data/relatef2.gz
cut -c91-91 data.dat | gzip -c - > data/edattan.gz
cut -c92-92 data.dat | gzip -c - > data/empstat.gz
cut -c93-94 data.dat | gzip -c - > data/occ.gz
cut -c95-96 data.dat | gzip -c - > data/hrswk.gz
cut -c97-97 data.dat | gzip -c - > data/classwk.gz
cut -c98-99 data.dat | gzip -c - > data/ind.gz
cut -c100-100 data.dat | gzip -c - > data/empsz.gz
cut -c101-101 data.dat | gzip -c - > data/seekjob.gz
cut -c102-104 data.dat | gzip -c - > data/seekdur.gz
cut -c105-108 data.dat | gzip -c - > data/jobendyr.gz
cut -c109-109 data.dat | gzip -c - > data/commw.gz
cut -c110-110 data.dat | gzip -c - > data/comms.gz
cut -c111-111 data.dat | gzip -c - > data/commdurw.gz
cut -c112-112 data.dat | gzip -c - > data/commdurs.gz
cut -c113-113 data.dat | gzip -c - > data/commloc.gz
cut -c114-114 data.dat | gzip -c - > data/relate.gz
cut -c115-116 data.dat | gzip -c - > data/famnum.gz
rm data.dat
echo "  End vectorizing: " `date`
