#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00109.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-26 data.dat | gzip -c - > data/dwnum.gz
cut -c27-27 data.dat | gzip -c - > data/pern.gz
cut -c28-29 data.dat | gzip -c - > data/region.gz
cut -c30-30 data.dat | gzip -c - > data/sizsettl.gz
cut -c31-31 data.dat | gzip -c - > data/urban.gz
cut -c32-32 data.dat | gzip -c - > data/owner.gz
cut -c33-33 data.dat | gzip -c - > data/hsgtype.gz
cut -c34-34 data.dat | gzip -c - > data/rooms.gz
cut -c35-35 data.dat | gzip -c - > data/space.gz
cut -c36-36 data.dat | gzip -c - > data/water.gz
cut -c37-37 data.dat | gzip -c - > data/sewage.gz
cut -c38-38 data.dat | gzip -c - > data/toilet.gz
cut -c39-39 data.dat | gzip -c - > data/bathroom.gz
cut -c40-40 data.dat | gzip -c - > data/gas.gz
cut -c41-41 data.dat | gzip -c - > data/phone.gz
cut -c42-42 data.dat | gzip -c - > data/cable.gz
cut -c43-43 data.dat | gzip -c - > data/heat.gz
cut -c44-44 data.dat | gzip -c - > data/fuelh.gz
cut -c45-45 data.dat | gzip -c - > data/bldty1.gz
cut -c46-46 data.dat | gzip -c - > data/bldty2.gz
cut -c47-47 data.dat | gzip -c - > data/bldyr.gz
cut -c48-48 data.dat | gzip -c - > data/numdwl.gz
cut -c49-51 data.dat | gzip -c - > data/pernum.gz
cut -c52-59 data.dat | gzip -c - > data/wtper.gz
cut -c60-60 data.dat | gzip -c - > data/pernum.gz
cut -c61-62 data.dat | gzip -c - > data/regionp.gz
cut -c63-63 data.dat | gzip -c - > data/areasizp.gz
cut -c64-64 data.dat | gzip -c - > data/bplind.gz
cut -c65-66 data.dat | gzip -c - > data/bpl.gz
cut -c67-67 data.dat | gzip -c - > data/bplctry.gz
cut -c68-68 data.dat | gzip -c - > data/immigyr.gz
cut -c69-69 data.dat | gzip -c - > data/resprt.gz
cut -c70-71 data.dat | gzip -c - > data/resprr.gz
cut -c72-72 data.dat | gzip -c - > data/resprc.gz
cut -c73-73 data.dat | gzip -c - > data/resdur.gz
cut -c74-74 data.dat | gzip -c - > data/res1yr.gz
cut -c75-75 data.dat | gzip -c - > data/relate.gz
cut -c76-76 data.dat | gzip -c - > data/relatef.gz
cut -c77-77 data.dat | gzip -c - > data/whyabs.gz
cut -c78-78 data.dat | gzip -c - > data/sex.gz
cut -c79-80 data.dat | gzip -c - > data/age.gz
cut -c81-81 data.dat | gzip -c - > data/marst.gz
cut -c82-82 data.dat | gzip -c - > data/citiz.gz
cut -c83-83 data.dat | gzip -c - > data/chborn.gz
cut -c84-84 data.dat | gzip -c - > data/school.gz
cut -c85-85 data.dat | gzip -c - > data/schloc.gz
cut -c86-86 data.dat | gzip -c - > data/stravm.gz
cut -c87-87 data.dat | gzip -c - > data/stravd.gz
cut -c88-88 data.dat | gzip -c - > data/edattan.gz
cut -c89-90 data.dat | gzip -c - > data/field.gz
cut -c91-91 data.dat | gzip -c - > data/empstat.gz
cut -c92-93 data.dat | gzip -c - > data/occ.gz
cut -c94-95 data.dat | gzip -c - > data/ind.gz
cut -c96-96 data.dat | gzip -c - > data/depend.gz
cut -c97-97 data.dat | gzip -c - > data/tenure.gz
cut -c98-98 data.dat | gzip -c - > data/workloc.gz
cut -c99-99 data.dat | gzip -c - > data/wtravf.gz
cut -c100-100 data.dat | gzip -c - > data/wtravm.gz
cut -c101-101 data.dat | gzip -c - > data/wtravd.gz
rm data.dat
echo "  End vectorizing: " `date`
