#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00078.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/pern.gz
cut -c31-31 data.dat | gzip -c - > data/fbig.gz
cut -c32-33 data.dat | gzip -c - > data/prov.gz
cut -c34-37 data.dat | gzip -c - > data/dist.gz
cut -c38-38 data.dat | gzip -c - > data/urban.gz
cut -c39-39 data.dat | gzip -c - > data/hhdeath.gz
cut -c40-40 data.dat | gzip -c - > data/deathtot.gz
cut -c41-41 data.dat | gzip -c - > data/floor.gz
cut -c42-45 data.dat | gzip -c - > data/area.gz
cut -c46-46 data.dat | gzip -c - > data/light.gz
cut -c47-47 data.dat | gzip -c - > data/fuelcook.gz
cut -c48-49 data.dat | gzip -c - > data/watdrink.gz
cut -c50-50 data.dat | gzip -c - > data/toilet.gz
cut -c51-51 data.dat | gzip -c - > data/septic.gz
cut -c52-52 data.dat | gzip -c - > data/phone.gz
cut -c53-53 data.dat | gzip -c - > data/internet.gz
cut -c54-54 data.dat | gzip -c - > data/tenure.gz
cut -c55-55 data.dat | gzip -c - > data/ownrshp.gz
cut -c56-56 data.dat | gzip -c - > data/ownproof.gz
cut -c57-57 data.dat | gzip -c - > data/doctype.gz
cut -c58-60 data.dat | gzip -c - > data/pernum.gz
cut -c61-68 data.dat | gzip -c - > data/wtper.gz
cut -c69-70 data.dat | gzip -c - > data/pernum.gz
cut -c71-72 data.dat | gzip -c - > data/relate.gz
cut -c73-73 data.dat | gzip -c - > data/sex.gz
cut -c74-75 data.dat | gzip -c - > data/birthmo.gz
cut -c76-79 data.dat | gzip -c - > data/birthyr.gz
cut -c80-81 data.dat | gzip -c - > data/age.gz
cut -c82-83 data.dat | gzip -c - > data/bthprov.gz
cut -c84-87 data.dat | gzip -c - > data/bthdist.gz
cut -c88-88 data.dat | gzip -c - > data/relig.gz
cut -c89-89 data.dat | gzip -c - > data/disblnd.gz
cut -c90-90 data.dat | gzip -c - > data/dishear.gz
cut -c91-91 data.dat | gzip -c - > data/disphys.gz
cut -c92-92 data.dat | gzip -c - > data/dismntl.gz
cut -c93-93 data.dat | gzip -c - > data/selfcare.gz
cut -c94-97 data.dat | gzip -c - > data/ethnic.gz
cut -c98-99 data.dat | gzip -c - > data/foreign.gz
cut -c100-101 data.dat | gzip -c - > data/prov5.gz
cut -c102-105 data.dat | gzip -c - > data/dist5.gz
cut -c106-109 data.dat | gzip -c - > data/lang.gz
cut -c110-110 data.dat | gzip -c - > data/speakind.gz
cut -c111-111 data.dat | gzip -c - > data/school.gz
cut -c112-113 data.dat | gzip -c - > data/educ.gz
cut -c114-114 data.dat | gzip -c - > data/litlatin.gz
cut -c115-115 data.dat | gzip -c - > data/litother.gz
cut -c116-116 data.dat | gzip -c - > data/marst.gz
cut -c117-117 data.dat | gzip -c - > data/econact.gz
cut -c118-118 data.dat | gzip -c - > data/tempwork.gz
cut -c119-119 data.dat | gzip -c - > data/seekwork.gz
cut -c120-120 data.dat | gzip -c - > data/willwork.gz
cut -c121-122 data.dat | gzip -c - > data/ind.gz
cut -c123-123 data.dat | gzip -c - > data/classwk.gz
cut -c124-124 data.dat | gzip -c - > data/livebth.gz
cut -c125-126 data.dat | gzip -c - > data/homemale.gz
cut -c127-128 data.dat | gzip -c - > data/homefem.gz
cut -c129-130 data.dat | gzip -c - > data/awaymale.gz
cut -c131-132 data.dat | gzip -c - > data/awayfem.gz
cut -c133-134 data.dat | gzip -c - > data/chdiedm.gz
cut -c135-136 data.dat | gzip -c - > data/chdiedf.gz
cut -c137-137 data.dat | gzip -c - > data/bthlstyr.gz
cut -c138-138 data.dat | gzip -c - > data/doctypep.gz
cut -c139-140 data.dat | gzip -c - > data/chbornm.gz
cut -c141-142 data.dat | gzip -c - > data/chbornf.gz
cut -c143-144 data.dat | gzip -c - > data/chborn.gz
cut -c145-146 data.dat | gzip -c - > data/chsurvm.gz
cut -c147-148 data.dat | gzip -c - > data/chsurvf.gz
cut -c149-150 data.dat | gzip -c - > data/chsurv.gz
rm data.dat
echo "  End vectorizing: " `date`
