#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00057.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-27 data.dat | gzip -c - > data/dwnum.gz
cut -c28-29 data.dat | gzip -c - > data/pern.gz
cut -c30-30 data.dat | gzip -c - > data/fbig.gz
cut -c31-32 data.dat | gzip -c - > data/prov.gz
cut -c33-33 data.dat | gzip -c - > data/urban.gz
cut -c34-34 data.dat | gzip -c - > data/hhtype.gz
cut -c35-37 data.dat | gzip -c - > data/usualhh.gz
cut -c38-39 data.dat | gzip -c - > data/visitors.gz
cut -c40-42 data.dat | gzip -c - > data/persons.gz
cut -c43-43 data.dat | gzip -c - > data/ownershp.gz
cut -c44-44 data.dat | gzip -c - > data/lighting.gz
cut -c45-45 data.dat | gzip -c - > data/fuel.gz
cut -c46-46 data.dat | gzip -c - > data/toilet.gz
cut -c47-47 data.dat | gzip -c - > data/watsrc.gz
cut -c48-48 data.dat | gzip -c - > data/watloc.gz
cut -c49-49 data.dat | gzip -c - > data/rooms.gz
cut -c50-51 data.dat | gzip -c - > data/radio.gz
cut -c52-53 data.dat | gzip -c - > data/tv.gz
cut -c54-55 data.dat | gzip -c - > data/phone.gz
cut -c56-57 data.dat | gzip -c - > data/cell.gz
cut -c58-59 data.dat | gzip -c - > data/pc.gz
cut -c60-61 data.dat | gzip -c - > data/bike.gz
cut -c62-63 data.dat | gzip -c - > data/motobike.gz
cut -c64-65 data.dat | gzip -c - > data/auto.gz
cut -c66-67 data.dat | gzip -c - > data/boat.gz
cut -c68-69 data.dat | gzip -c - > data/tractor.gz
cut -c70-71 data.dat | gzip -c - > data/handtrac.gz
cut -c72-72 data.dat | gzip -c - > data/nethome.gz
cut -c73-73 data.dat | gzip -c - > data/netaway.gz
cut -c74-74 data.dat | gzip -c - > data/deaths.gz
cut -c75-77 data.dat | gzip -c - > data/pernum.gz
cut -c78-85 data.dat | gzip -c - > data/wtper.gz
cut -c86-87 data.dat | gzip -c - > data/pernum.gz
cut -c88-88 data.dat | gzip -c - > data/relate.gz
cut -c89-89 data.dat | gzip -c - > data/sex.gz
cut -c90-91 data.dat | gzip -c - > data/age.gz
cut -c92-92 data.dat | gzip -c - > data/marst.gz
cut -c93-94 data.dat | gzip -c - > data/mtongue.gz
cut -c95-95 data.dat | gzip -c - > data/relig.gz
cut -c96-97 data.dat | gzip -c - > data/bplprov.gz
cut -c98-101 data.dat | gzip -c - > data/bpldist.gz
cut -c102-103 data.dat | gzip -c - > data/prevprov.gz
cut -c104-107 data.dat | gzip -c - > data/prevdist.gz
cut -c108-109 data.dat | gzip -c - > data/durres.gz
cut -c110-111 data.dat | gzip -c - > data/migreas.gz
cut -c112-112 data.dat | gzip -c - > data/litkh.gz
cut -c113-113 data.dat | gzip -c - > data/litoth.gz
cut -c114-114 data.dat | gzip -c - > data/school.gz
cut -c115-116 data.dat | gzip -c - > data/educ.gz
cut -c117-117 data.dat | gzip -c - > data/disbrth.gz
cut -c118-118 data.dat | gzip -c - > data/disafter.gz
cut -c119-119 data.dat | gzip -c - > data/empstat.gz
cut -c120-121 data.dat | gzip -c - > data/empmo.gz
cut -c122-124 data.dat | gzip -c - > data/occ.gz
cut -c125-125 data.dat | gzip -c - > data/classwk.gz
cut -c126-128 data.dat | gzip -c - > data/ind.gz
cut -c129-129 data.dat | gzip -c - > data/empsect.gz
cut -c130-131 data.dat | gzip -c - > data/sececon.gz
cut -c132-132 data.dat | gzip -c - > data/workloc.gz
cut -c133-134 data.dat | gzip -c - > data/workprov.gz
cut -c135-138 data.dat | gzip -c - > data/workdist.gz
cut -c139-140 data.dat | gzip -c - > data/chbornm.gz
cut -c141-142 data.dat | gzip -c - > data/chbornf.gz
cut -c143-144 data.dat | gzip -c - > data/chsurvm.gz
cut -c145-146 data.dat | gzip -c - > data/chsurvf.gz
cut -c147-148 data.dat | gzip -c - > data/chdeadm.gz
cut -c149-150 data.dat | gzip -c - > data/chdeadf.gz
cut -c151-151 data.dat | gzip -c - > data/maleborn.gz
cut -c152-152 data.dat | gzip -c - > data/femborn.gz
cut -c153-153 data.dat | gzip -c - > data/assistb.gz
rm data.dat
echo "  End vectorizing: " `date`
