#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00075.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/pern.gz
cut -c31-31 data.dat | gzip -c - > data/fbig.gz
cut -c32-32 data.dat | gzip -c - > data/regionn.gz
cut -c33-33 data.dat | gzip -c - > data/region.gz
cut -c34-35 data.dat | gzip -c - > data/prefect.gz
cut -c36-36 data.dat | gzip -c - > data/urban.gz
cut -c37-37 data.dat | gzip -c - > data/hhtype.gz
cut -c38-39 data.dat | gzip -c - > data/pnmp.gz
cut -c40-41 data.dat | gzip -c - > data/pnma.gz
cut -c42-43 data.dat | gzip -c - > data/pnmv.gz
cut -c44-45 data.dat | gzip -c - > data/pnfp.gz
cut -c46-47 data.dat | gzip -c - > data/pnfa.gz
cut -c48-49 data.dat | gzip -c - > data/pnfv.gz
cut -c50-50 data.dat | gzip -c - > data/tenure.gz
cut -c51-51 data.dat | gzip -c - > data/watsup.gz
cut -c52-52 data.dat | gzip -c - > data/light.gz
cut -c53-53 data.dat | gzip -c - > data/fuelck.gz
cut -c54-54 data.dat | gzip -c - > data/toilet.gz
cut -c55-55 data.dat | gzip -c - > data/garbage.gz
cut -c56-56 data.dat | gzip -c - > data/wastewat.gz
cut -c57-57 data.dat | gzip -c - > data/sewage.gz
cut -c58-59 data.dat | gzip -c - > data/rooms.gz
cut -c60-60 data.dat | gzip -c - > data/sexd.gz
cut -c61-63 data.dat | gzip -c - > data/aged.gz
cut -c64-66 data.dat | gzip -c - > data/pernum.gz
cut -c67-74 data.dat | gzip -c - > data/wtper.gz
cut -c75-75 data.dat | gzip -c - > data/resident.gz
cut -c76-77 data.dat | gzip -c - > data/pernum.gz
cut -c78-79 data.dat | gzip -c - > data/pernumo.gz
cut -c80-81 data.dat | gzip -c - > data/relate.gz
cut -c82-82 data.dat | gzip -c - > data/sex.gz
cut -c83-83 data.dat | gzip -c - > data/resid.gz
cut -c84-85 data.dat | gzip -c - > data/birmon.gz
cut -c86-87 data.dat | gzip -c - > data/biryr.gz
cut -c88-90 data.dat | gzip -c - > data/ageraw.gz
cut -c91-92 data.dat | gzip -c - > data/bpl.gz
cut -c93-94 data.dat | gzip -c - > data/nation.gz
cut -c95-95 data.dat | gzip -c - > data/relig.gz
cut -c96-97 data.dat | gzip -c - > data/disab.gz
cut -c98-98 data.dat | gzip -c - > data/resdur.gz
cut -c99-100 data.dat | gzip -c - > data/resprev.gz
cut -c101-102 data.dat | gzip -c - > data/lit.gz
cut -c103-103 data.dat | gzip -c - > data/edlev2.gz
cut -c104-105 data.dat | gzip -c - > data/grade.gz
cut -c106-107 data.dat | gzip -c - > data/edattan.gz
cut -c108-109 data.dat | gzip -c - > data/empstat.gz
cut -c110-112 data.dat | gzip -c - > data/occ.gz
cut -c113-114 data.dat | gzip -c - > data/classwk.gz
cut -c115-116 data.dat | gzip -c - > data/marst.gz
cut -c117-118 data.dat | gzip -c - > data/chbornm.gz
cut -c119-120 data.dat | gzip -c - > data/chbornf.gz
cut -c121-122 data.dat | gzip -c - > data/chsurvm.gz
cut -c123-124 data.dat | gzip -c - > data/chsurvf.gz
cut -c125-125 data.dat | gzip -c - > data/chb12m.gz
cut -c126-126 data.dat | gzip -c - > data/chb12f.gz
cut -c127-129 data.dat | gzip -c - > data/age.gz
rm data.dat
echo "  End vectorizing: " `date`
