#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00080.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00080.dat.gz.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-28 data.dat | gzip -c - > data/dwnum.gz
cut -c29-30 data.dat | gzip -c - > data/pern.gz
cut -c31-31 data.dat | gzip -c - > data/fbig.gz
cut -c32-33 data.dat | gzip -c - > data/gov.gz
cut -c34-37 data.dat | gzip -c - > data/qad.gz
cut -c38-38 data.dat | gzip -c - > data/urban.gz
cut -c39-40 data.dat | gzip -c - > data/hhno.gz
cut -c41-42 data.dat | gzip -c - > data/roombed.gz
cut -c43-43 data.dat | gzip -c - > data/owner.gz
cut -c44-44 data.dat | gzip -c - > data/dwsize.gz
cut -c45-50 data.dat | gzip -c - > data/rent.gz
cut -c51-51 data.dat | gzip -c - > data/dwtype.gz
cut -c52-52 data.dat | gzip -c - > data/walls.gz
cut -c53-54 data.dat | gzip -c - > data/rooms.gz
cut -c55-55 data.dat | gzip -c - > data/bath.gz
cut -c56-56 data.dat | gzip -c - > data/toilet.gz
cut -c57-57 data.dat | gzip -c - > data/batht.gz
cut -c58-58 data.dat | gzip -c - > data/kitch.gz
cut -c59-59 data.dat | gzip -c - > data/elect.gz
cut -c60-60 data.dat | gzip -c - > data/phone.gz
cut -c61-61 data.dat | gzip -c - > data/watsrc.gz
cut -c62-62 data.dat | gzip -c - > data/sewer.gz
cut -c63-63 data.dat | gzip -c - > data/dwtyc.gz
cut -c64-66 data.dat | gzip -c - > data/pernum.gz
cut -c67-74 data.dat | gzip -c - > data/wtper.gz
cut -c75-75 data.dat | gzip -c - > data/resident.gz
cut -c76-77 data.dat | gzip -c - > data/pernum.gz
cut -c78-78 data.dat | gzip -c - > data/resstat.gz
cut -c79-80 data.dat | gzip -c - > data/relate.gz
cut -c81-81 data.dat | gzip -c - > data/sex.gz
cut -c82-83 data.dat | gzip -c - > data/birthm.gz
cut -c84-87 data.dat | gzip -c - > data/birthy.gz
cut -c88-88 data.dat | gzip -c - > data/marst.gz
cut -c89-92 data.dat | gzip -c - > data/maryr.gz
cut -c93-93 data.dat | gzip -c - > data/marn.gz
cut -c94-94 data.dat | gzip -c - > data/wives.gz
cut -c95-96 data.dat | gzip -c - > data/mardur.gz
cut -c97-98 data.dat | gzip -c - > data/chbornm.gz
cut -c99-100 data.dat | gzip -c - > data/chbornf.gz
cut -c101-102 data.dat | gzip -c - > data/chlivm.gz
cut -c103-104 data.dat | gzip -c - > data/chlivf.gz
cut -c105-105 data.dat | gzip -c - > data/chbornrm.gz
cut -c106-106 data.dat | gzip -c - > data/chbornrf.gz
cut -c107-107 data.dat | gzip -c - > data/empstat.gz
cut -c108-110 data.dat | gzip -c - > data/occ.gz
cut -c111-113 data.dat | gzip -c - > data/ind.gz
cut -c114-114 data.dat | gzip -c - > data/classwk.gz
cut -c115-115 data.dat | gzip -c - > data/sector.gz
cut -c116-116 data.dat | gzip -c - > data/fulltime.gz
cut -c117-117 data.dat | gzip -c - > data/incsrc.gz
cut -c118-118 data.dat | gzip -c - > data/parliv.gz
cut -c119-121 data.dat | gzip -c - > data/bpl.gz
cut -c122-122 data.dat | gzip -c - > data/resdur.gz
cut -c123-124 data.dat | gzip -c - > data/resdury.gz
cut -c125-127 data.dat | gzip -c - > data/respr.gz
cut -c128-128 data.dat | gzip -c - > data/respru.gz
cut -c129-130 data.dat | gzip -c - > data/whymove.gz
cut -c131-133 data.dat | gzip -c - > data/res87.gz
cut -c134-134 data.dat | gzip -c - > data/res87u.gz
cut -c135-137 data.dat | gzip -c - > data/nation.gz
cut -c138-139 data.dat | gzip -c - > data/edlev1.gz
cut -c140-140 data.dat | gzip -c - > data/edgrade.gz
cut -c141-143 data.dat | gzip -c - > data/edattan.gz
cut -c144-144 data.dat | gzip -c - > data/lit.gz
cut -c145-146 data.dat | gzip -c - > data/edlev2.gz
cut -c147-148 data.dat | gzip -c - > data/handicap.gz
cut -c149-151 data.dat | gzip -c - > data/age.gz
cut -c152-153 data.dat | gzip -c - > data/lang.gz
rm data.dat
echo "  End vectorizing: " `date`
