# working.script.R - GF - 04-Jan-2015

rm(list=ls())
setwd("C:/Users/gfeeney/Desktop/ipums.aye")
setwd("processing/Rfunctions1/")
source("status.R")
source("variable.metadata.autocreate.R")
source("variables.metadata.autogenerated.create.R")
setwd("../Rfunctions2")
source("getcodebook.R")
source("getvariable.R")
setwd("../../")

setwd("samples")
samplename <- "armenia2001"
setwd(samplename)
codebook <- readRDS("metadata/codebook.rds")
variables <- readRDS("metadata/vnames.vdescriptions.rds")
vnames <- variables[, "vname"]
vnames <- vnames[4:length(vnames)]

variables.metadata.autogenerated.create()



