#!/bin/sh
# Vectorize data file
echo "Begin vectorizing: " `date`
gunzip -c source/ipumsi_00095.dat.gz > data.dat
sha1sum data.dat > source/ipumsi_00.sha1
mkdir data
cut -c1-3 data.dat | gzip -c - > data/cntry.gz
cut -c4-7 data.dat | gzip -c - > data/year.gz
cut -c8-11 data.dat | gzip -c - > data/sample.gz
cut -c12-21 data.dat | gzip -c - > data/serial.gz
cut -c22-27 data.dat | gzip -c - > data/dwnum.gz
cut -c28-30 data.dat | gzip -c - > data/pernum.gz
cut -c31-38 data.dat | gzip -c - > data/wtper.gz
cut -c39-39 data.dat | gzip -c - > data/pernum.gz
cut -c40-40 data.dat | gzip -c - > data/sex.gz
cut -c41-42 data.dat | gzip -c - > data/age.gz
cut -c43-43 data.dat | gzip -c - > data/relate.gz
cut -c44-44 data.dat | gzip -c - > data/hhsize.gz
cut -c45-45 data.dat | gzip -c - > data/resprev.gz
cut -c46-46 data.dat | gzip -c - > data/citz.gz
cut -c47-47 data.dat | gzip -c - > data/bpl.gz
cut -c48-48 data.dat | gzip -c - > data/educ.gz
cut -c49-49 data.dat | gzip -c - > data/classwk.gz
cut -c50-51 data.dat | gzip -c - > data/occ.gz
cut -c52-53 data.dat | gzip -c - > data/ind.gz
cut -c54-54 data.dat | gzip -c - > data/marst.gz
cut -c55-69 data.dat | gzip -c - > data/weight.gz
rm data.dat
echo "  End vectorizing: " `date`
